using Microsoft.Maui.Controls;
using R3;
using R3Ext.Activation;
using R3Ext.Bindings;
using R3Ext.Maui;
using R3Ext.SampleApp.ViewModels;

// Resolve ambiguity with Microsoft.Maui.ActivationState
using ActivationState = R3Ext.Activation.ActivationState;

namespace R3Ext.SampleApp;

/// <summary>
/// Demonstrates the <see cref="IViewFor{TViewModel}"/> pattern with automatic ViewModel activation.
/// This page shows how to use the activation lifecycle to manage subscriptions and resources.
/// The source generator automatically provides:
/// - ViewModel property with BindingContext sync.
/// - Activation property for lifecycle events.
/// - InitializeViewFor() helper.
/// </summary>
public partial class ActivationDemoPage : ContentPage, IViewFor<ActivationDemoViewModel>
{
    private int _attachedCount;

    public ActivationDemoPage()
    {
        InitializeComponent();

        // Create and set the ViewModel
        // Note: For DI, you could resolve this from IServiceProvider instead
        ViewModel = new ActivationDemoViewModel();

        // Set up view-side WhenActivated using extension method syntax
        // This pattern automatically handles:
        // 1. Activating the ViewModel when the page appears
        // 2. Disposing subscriptions when the page disappears
        // 3. Re-activating when the page appears again
        // 4. Late-bound ViewModels (ViewModel can be set after construction)
        // 5. Auto-cleanup when the page is destroyed (no manual disposal needed!)
        this.WhenAttached(
            (ref DisposableBag disposables) =>
            {
                // Method 1: R3Ext bindings with this.BindOneWay() - works with source-generated ViewModel!
                // The BindingGenerator resolves ViewModel from the IViewFor<T> interface
                this.BindOneWay(StatusLabel, v => v.ViewModel!.ActivationStatus.CurrentValue, l => l.Text)
                    .AddTo(ref disposables);

                this.BindOneWay(TimerLabel, v => v.ViewModel!.TimerValue.CurrentValue, l => l.Text)
                    .AddTo(ref disposables);

                // Method 2: Direct observable subscription - also valid for ReactiveProperty
                // This is more direct for properties that are already Observable<T>
                ViewModel!.IsTimerRunning
                    .Subscribe(running => TimerStatusLabel.Text = running ? "Timer is running..." : "Timer stopped")
                    .AddTo(ref disposables);

                ViewModel!.ActivationCount
                    .Subscribe(count => ActivationCountLabel.Text = count.ToString())
                    .AddTo(ref disposables);

                ViewModel.DeactivationCount
                    .Subscribe(count => DeactivationCountLabel.Text = count.ToString())
                    .AddTo(ref disposables);
            });

        // WhenAttached uses Loaded/Unloaded events instead of Appearing/Disappearing
        // This is useful for one-time setup that requires the visual tree to be ready
        // Also auto-cleans up when the page is destroyed
        this.WhenActivated(
            (ref DisposableBag disposables) =>
            {
                _attachedCount++;
                AttachedCountLabel.Text = _attachedCount.ToString();

                // Cleanup on detach
                Disposable.Create(() =>
                {
                    // Could log or track detachment here
                }).AddTo(ref disposables);
            });
    }

    // NOTE: The following members are now generated by the source generator:
    // - ViewModel property (with BindingContext sync)
    // - AutoActivateViewModel property
    // - IActivatable.Activation property
}
